# Generated by Django 3.0.7 on 2020-06-17 19:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500, verbose_name='խմբի անվանումը')),
                ('group_slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8)),
            ],
            options={
                'verbose_name': 'խումբ',
                'verbose_name_plural': 'խմբեր',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=256, verbose_name='անուն')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'հղում',
                'verbose_name_plural': 'հղումներ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256, verbose_name='տիպ')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group', verbose_name='խումբ')),
            ],
            options={
                'verbose_name': 'տիպ',
                'verbose_name_plural': 'տիպեր',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700, verbose_name='վերնագիր')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8)),
                ('img', models.ImageField(upload_to='', verbose_name='նկար')),
                ('body', models.TextField(verbose_name='տեքստ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='օր/ամիս/տարեթիվ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group', verbose_name='խումբ')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Type', verbose_name='տիպ')),
            ],
            options={
                'verbose_name': 'գրառում',
                'verbose_name_plural': 'գրառումներ',
                'managed': True,
            },
        ),
    ]
