# Generated by Django 3.0.7 on 2020-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ManyToManyField(to='app.Type', verbose_name='տիպ'),
        ),
    ]
