# Generated by Django 3.0.7 on 2020-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200618_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ManyToManyField(blank=True, to='app.Type', verbose_name='տիպ'),
        ),
    ]
